# Generated by Django 4.1.3 on 2023-01-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.PositiveIntegerField()),
                ('customer', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=12)),
                ('payment', models.CharField(default='cash', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ManyToManyField(to='main.product')),
            ],
        ),
    ]
