# Generated by Django 4.1.3 on 2023-01-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('ref', models.PositiveIntegerField()),
            ],
        ),
    ]
