# Generated by Django 4.1.3 on 2023-01-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_invoiceproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='goods',
            field=models.ManyToManyField(to='main.invoiceproduct'),
        ),
    ]
